[project]
name = "ai-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.4.0",
]
[tool.pyright]
venvPath = "."
venv = ".venv"
dependencies = ["ollama>=0.5.2"]
